### Site metadata ###

site_name: SlimFit
site_description: SymFit's little brother
site_url: https://jhsmit.github.io/slimfit/

repo_url: https://github.com/Jhsmit/slimfit
edit_uri: edit/master/docs/

### Build settings ###

theme:
  name: material

markdown_extensions:
  - codehilite
  - markdown.extensions.codehilite:
      guess_lang: false

nav:
  - Home: index.md
  - Installation: installation.md
#  - API Reference: api.md


#plugins:
#  - mkdocstrings:
#      handlers:
#        python:
#          paths: [slimfit]


extra_css:
- css/styles.css
